# Generated by Django 3.1.1 on 2020-10-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201006_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcollection',
            options={},
        ),
    ]
