# Generated by Django 3.1.1 on 2020-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='body',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
